### ISSUE TITLE
Task: V1

### ISSUE THREAD

**Issue by bookey-admin** [bookey-dev/bookey.docs#2]
## 每周计划

**评论模版**

```md

**IOS**
- [ ] 任务1

---

**Android**
- [ ] 任务1

---

**Web**
- [ ] 任务1

---
```

**Comment by Johnsonkk2020** [comment]
- [ ] Google营销下载链接短信发送页的WEB页面。需要考虑国家区号的下拉菜单。如暂无法解决下拉菜单，先以美国为准。

- [ ] 非订阅用户每本书第一段音频结束时添加一段音频，以提示用户订阅。在所有书籍最后一段音频结束后添加一段音频，以提示用户分享。

- [ ] 受苹果规则影响，分享激励规则修改，被分享者的10天奖励需要取消。前端UI及后端逻辑规则均要去掉这规则，但其他记录的点不变。

- [ ] 跨级订阅功能，由月订升级为年订以及年订降级为月订的需求需要满足用户。

- [ ] 用户注册20天后，分享激励活动的Banner需要自动隐藏。

**Comment by Johnsonkk2020** [comment]
- [ ] Stephen：完成MARK功能，包括前端UI及接口调试。

- [ ] Stephen：完成每日一本免费书籍的前商UI部分。

- [ ] Stephen：其他需求及优化。

- [ ] Kim：MARK接口布置，供前端开发测试。

- [ ] Kim：基于阿里云的短信功能集成。

- [ ] Kim：Pinpoint的进一步实现。

- [ ] ALL：新增埋点，并统一名称及具体动作。
