### ISSUE TITLE
43 周

### ISSUE THREAD

**Issue by itwangxiang** [bookey-dev/bookey.docs#32]
- [ ] 答题
  - [x] 后台维护页面
  - [x] 修改书籍详情页 API - 新增答题内容、是否答过题
  - [x] 新增答题记录 API - 答题时长、答题的题目数量、正确答题数量
- [x] submit-rate 的埋点
- [ ] 解决 - 订阅的 保留期

**Comment by Coolll** [comment]
- [ ] iOS的推送权限引导图

- [ ] 答题的优化

**Comment by Johnsonkk2020** [comment]
- [ ] submit-rate的埋点
@itwangxiang @Coolll

**Comment by Johnsonkk2020** [comment]
![Uploading 微信图片_20201020093337.png…]()

**Comment by Johnsonkk2020** [comment]
新增埋点：
1、quiz按钮的点击事件：分为未完成书籍时的点击和完成书籍后的点击
2、第一次全部答对后弹窗的VIEW事件
3、非第一次全部答对后弹窗的VIEW事件
总计4个点
@itwangxiang @Coolll
