### ISSUE TITLE
等 48 周

### ISSUE THREAD

**Issue by itwangxiang** [bookey-dev/bookey.docs#37]
#### UI

- [ ] xxx

#### IOS

- [ ] xxx

#### Android

- [x] 应用市场 - 宣传图替换
- [ ] mark 完一本书后的 share 改成书籍详情页的 deepview

**Comment by itwangxiang** [comment]
- [ ] 阅读迷你 Bar

**Comment by Coolll** [comment]
- [ ]  商店图更新

- [ ] 订阅折扣开发

- [ ] iWatch开发
