### ISSUE TITLE
Release: V1

### ISSUE THREAD

**Issue by itwangxiang** [bookey-dev/bookey.docs#5]
### Android - [版本记录](https://github.com/bookey-dev/bookey.docs/issues/5#issuecomment-637493917)

---

**评论模版**

```md
### v1.?

**功能描述**
1. 新增 - ???????????
1. 修复 - ???????????
1. 优化 - ???????????
1. 其他 - ???????????

---

```

**Comment by itwangxiang** [comment]
### v1.1.529

**功能描述**

1. 新增 - 非会员用户播放完第一章，播放订阅引导语
1. 新增 - 会员用户播放完后，播放结束语
1. 新增 - 非会员用户点击下一章，弹出订阅弹出
1. 新增 - 分享推荐活动终止后，将 `share` 类型的Banner 隐藏掉
1. 优化 - 播放逻辑

**Comment by pengxiaoyan** [comment]
### v1.1.2 - [Download](https://www.pgyer.com/hwqs)

**功能描述**

1 新增  苹果端 用户 订单升降级
2 新增  非订阅用户 播放完成第一章节播放提示音频
3 新增  用户听完一本书 播放提示音频
4 新增  应苹果审核 修改十天激励 UI
5 新增  用户达成分享激励后 首页分享banner 隐藏
6 新增 新增首页刷新功能

**Comment by pengxiaoyan** [comment]
### iOS v1.1.2 - [Download](https://www.pgyer.com/hwqs)

**功能描述**

1. 修复 - 好友分享任务达成弹窗,只在share页展示
2. 修复 - 修改UI问题
3. 优化 - 弱网环境播放问题
4  新增 firebase 第三方崩溃分析工具

**Comment by itwangxiang** [comment]
### v1.1.601

**功能描述**

1. 修复 - 会员有效期结束后，重新打开 APP，恢复非第一章音频时闪退问题
1. 修复 - Firebase 的一些 BUG
1. 其他 - 细分分享的事件名
1. 其他 - 开发版新增 API  切换功能

---

### v1.1.529

**功能描述**

1. 新增 - 非会员用户播放完第一章，播放订阅引导语
1. 新增 - 会员用户播放完后，播放结束语
1. 新增 - 非会员用户点击下一章，弹出订阅弹出
1. 新增 - 用户达成分享激励后，将首页 Share 类型的 Banner 过滤掉掉
1. 优化 - 播放逻辑

**Comment by pengxiaoyan** [comment]
v1.1.608

**功能描述**
1. 新增 - 书本mark功能 (仅测试环境)
2. 新增 - 首页每日一本UI (暂无真实接口) 
3.新增 - setting页 跳转Facebook 和 Instagram 运营账户
4 优化 - 优化UI

**Comment by pengxiaoyan** [comment]
> ## Release: V1
> ### IOS - [版本记录](https://github.com/bookey-dev/bookey.docs/issues/5#issuecomment-635845044)
> ### Android - [版本记录](https://github.com/bookey-dev/bookey.docs/issues/5#issuecomment-637493917)
> **评论模版**
> 
> ```lisp
> ### v1.?
> 
> **功能描述**
> 1. 新增 - ???????????
> 1. 修复 - ???????????
> 1. 优化 - ???????????
> 1. 其他 - ???????????
> 
> ---
> ```

测试

**Comment by Johnsonkk2020** [comment]
6.19

IOS update description:
   1. New: Mark finished after reading one bookey
   2. New: You can share bookey and keep reading other bookey after mark finished
   3. New: Sharing function added at play page and reading page
   4. Optimization: optimize reading layout style to make reading more comfortable
   5. Modification: Optimize some part of UI


Android update description:
   1. New: Sharing function added at play page and reading page

**Comment by Johnsonkk2020** [comment]
IOS
@pengxiaoyan 
1、Optimize the layout of read page text；
2、Optimize referral links when user share the bookey content。
Android
@itwangxiang 
1、Optimize referral links when user share the bookey content；
2、Added button to follow Bookey's FACEBOOK and INSTAGRAM at setting page。

**Comment by Johnsonkk2020** [comment]
7.10
IOS
New - User could enjoy one free bookey per day at Daily Mind Snack.
New - Better UI for iPad.

**Comment by Johnsonkk2020** [comment]
20200731版本更新内容
1. Add Collections （bookey list）in Discover page which helps user choose the bookey more easily.
2. Update the layout of Discover page.
